[package]
name = "exercise"
version = "0.1.0"
authors = ["Tyler Neely <t@jujit.su>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
model = "0.1.2"
nats = { version = "0.9.4", features = ["jetstream"] }
